GET http://localhost:5004/article

###

GET http://localhost:3333/article/1fa9eca6-9699-4778-91a6-c34f7a7859f5
###

POST http://localhost:5004/article
Content-Type: application/json

 {
  "nickname": "테스트판다",
  "title": "이 글을 테스트하겠습니다",
  "content": "테스트12345",
  "image": ""
 }

###

PATCH http://localhost:3333/article/1fa9eca6-9699-4778-91a6-c34f7a7859f5
Content-Type: application/json

{
  "nickname": "귀여운판다",
}

###

DELETE http://localhost:3333/article/787b4aa1-4a8b-4f76-8b0d-556d24d4f58e